name: bstree - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.3'

    - name: Display Go version
      run: go version

    - name: Fetch dependencies
      run: go mod download

    - name: Run tests
      run: go clean -testcache ./... && go test -v ./...

  tests-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.3'

    - name: Display Go version
      run: go version

    - name: Fetch dependencies
      run: go mod download

    - name: Run tests
      run: go clean -testcache ./... && go test -v ./...

  tests-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.3'

    - name: Display Go version
      run: go version

    - name: Fetch dependencies
      run: go mod download

    - name: Run tests
      run: go clean -testcache ./... && go test -v ./...
